[[Thrift]]
arch = "aarch64"
git-tree-sha1 = "760a0052f6baa49b1511cc4ff14a79514a44f302"
os = "macos"

    [[Thrift.download]]
    sha256 = "bf549760357d38ff6f6ce48ec9eacf083786a7f737eed754551684e7a69ee58e"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.aarch64-apple-darwin.tar.gz"
[[Thrift]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a17448eba85e2feb681cc04e3c8a7599441c6f9"
libc = "glibc"
os = "linux"

    [[Thrift.download]]
    sha256 = "a286cd55c3e33b17d3d1c32d73e86890abffd66c6100905dc2e1698194c42973"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Thrift]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "440c0afb91ec4a26cf9899cb41f6d1e8d83a4402"
libc = "glibc"
os = "linux"

    [[Thrift.download]]
    sha256 = "2ab2c76b877bf8c007fdc6e235cbd1cef80e43125e3a10a3b68d0256dc18435a"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Thrift]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03fdfb09db039b8ab148aff64ab728738948134b"
libc = "musl"
os = "linux"

    [[Thrift.download]]
    sha256 = "bdecdf3389586649eeb44ff8db05b0be7f5176f56a9d145f8ac2151de550208e"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.aarch64-linux-musl-cxx03.tar.gz"
[[Thrift]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2d202969c4f453dcf64756a7f0f78d90b605339"
libc = "musl"
os = "linux"

    [[Thrift.download]]
    sha256 = "7309674ed6326fc39badd34010330f16754e93642fbc10a298b3fb30e25e113d"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.aarch64-linux-musl-cxx11.tar.gz"
[[Thrift]]
arch = "aarch64"
git-tree-sha1 = "593af3120a0dbed3c015426ea01351b0b6c187c5"
os = "freebsd"

    [[Thrift.download]]
    sha256 = "82be0fd8a453d34fd133ec4e4ce5197520c2bf301ef049f9319b9b3ed39cbde2"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.aarch64-unknown-freebsd.tar.gz"
[[Thrift]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a2f849cc83a4aedab9350d2f710becaeb24f6ce"
libc = "glibc"
os = "linux"

    [[Thrift.download]]
    sha256 = "c38e321a2836faf6ace95f30844b29b055fb85c4edc632144f1274760102f2ee"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Thrift]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08ae2d52cbcc5b5feeb4a2e8ba8e43172eea77d0"
libc = "glibc"
os = "linux"

    [[Thrift.download]]
    sha256 = "297698da8132ff05ec21ce60cd4e3b503ae6624f1eaf77b7f7a73e4fba75e5f2"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Thrift]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5054888c18fa7bc6be3c64d98bd30d85c3445f5f"
libc = "musl"
os = "linux"

    [[Thrift.download]]
    sha256 = "2b6f11e5fbe5d43727fd6cf14d952d5f4b8b4b659cc3939f55a65217574aa9e0"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Thrift]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "231cb359c821ef7bb2635fdb0f3b37e78726adb1"
libc = "musl"
os = "linux"

    [[Thrift.download]]
    sha256 = "2c150d01f2191ed33076cf77ca66564ecc52f4f4fb627fb4e12bb8302e5af57b"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Thrift]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8adc86f966d9d777b30f57ced64524648d06277a"
libc = "glibc"
os = "linux"

    [[Thrift.download]]
    sha256 = "c1acd60f7f95e01331bc89b135c73f9b9a7867efc250d568a1e17ff46d02e7cd"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Thrift]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "159f1569539039be02567bf807998fb9ea00ad71"
libc = "glibc"
os = "linux"

    [[Thrift.download]]
    sha256 = "d0f492aa921014395a6ecae4eb24510aab07948b1197d3093c8835855bced5ad"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Thrift]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a937fc317a103a54419fb4d6875910d134b406b2"
libc = "musl"
os = "linux"

    [[Thrift.download]]
    sha256 = "575d23a1df333d9ff707f77efa6ad75912a4c6b213f0ac9eb76e26c8b98f38bd"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Thrift]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3e8d2ff0d8366503b07eb85a0ce3132b202c5c3"
libc = "musl"
os = "linux"

    [[Thrift.download]]
    sha256 = "73692487025d3833b954838c3b5178730fb39cdfc98e1b79da9f5c18ef774862"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Thrift]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa3db45ccfe356ca9d45e1cd84d67e0aafcc304c"
libc = "glibc"
os = "linux"

    [[Thrift.download]]
    sha256 = "b542ea7a2ec1cab667291a4896cd6c9ef051c072a60cb91129ac8687d62b4a71"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.i686-linux-gnu-cxx03.tar.gz"
[[Thrift]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb1587972ab315d4c9b7c1697cf0a9f1c37dab0c"
libc = "glibc"
os = "linux"

    [[Thrift.download]]
    sha256 = "7d30cf5d9e640d76d77093d02a8a05ae7cb7f9a2e6fa301072580ca192f520cc"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.i686-linux-gnu-cxx11.tar.gz"
[[Thrift]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1742450383424b2fd1945feca840a17cbaeee13"
libc = "musl"
os = "linux"

    [[Thrift.download]]
    sha256 = "e3eacdade8f6eadb430c647e0439ab5e2174f16ecf98346114aea04ad36522f1"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.i686-linux-musl-cxx03.tar.gz"
[[Thrift]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4a7e0487218aa64d700f8bb22f64aa4fb9a8ea6"
libc = "musl"
os = "linux"

    [[Thrift.download]]
    sha256 = "8fe8b5bfd3d65ef9b7ccd12ed2ebdc101f710801b279a2faed66d694d32c5fcd"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.i686-linux-musl-cxx11.tar.gz"
[[Thrift]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e15ffd752281e68c14538fc2687981f14434bfc5"
os = "windows"

    [[Thrift.download]]
    sha256 = "f7fcc3959940e5d9f7a539a76a21e3603f2d5cf4e67aeb62cfe10a793ee9ff11"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.i686-w64-mingw32-cxx03.tar.gz"
[[Thrift]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d7c149b7018c5959229cc440b2d379f6928bfa7"
os = "windows"

    [[Thrift.download]]
    sha256 = "e9b05c6eab375c8a2361bf17891805092e9303d19d009400b1b64ee26a65654f"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.i686-w64-mingw32-cxx11.tar.gz"
[[Thrift]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9b9e2d09d66b618bdf1d00f2769d925696acad4"
libc = "glibc"
os = "linux"

    [[Thrift.download]]
    sha256 = "787b66b230cb9bc6932144c0e96ccad453035e3366c954bd5bab9799e4e55d26"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Thrift]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c77941cbd49d16837b95dce1ef0aaf7e67b92263"
libc = "glibc"
os = "linux"

    [[Thrift.download]]
    sha256 = "3263c7341778671d3875dee4ac4ca040cac39b97b7a697cf6332780252c8aa4c"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Thrift]]
arch = "x86_64"
git-tree-sha1 = "4dabc437dd0e3025613bf5af4ec718b2ef424ce0"
os = "macos"

    [[Thrift.download]]
    sha256 = "32aa257e34076c573bd19cddf2c61ecaef01d2c682ac6ade32fb18d88b8fa865"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.x86_64-apple-darwin.tar.gz"
[[Thrift]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bd30585530b13fa633ff9bf0d36a92cf6be37c7"
libc = "glibc"
os = "linux"

    [[Thrift.download]]
    sha256 = "72b4c21e3d53e39bbb9f8bac3fb472ae79197c22cac20a0633202fcdafc7ab1a"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Thrift]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2726381ede50480f7210163e9d39272c9e7a53eb"
libc = "glibc"
os = "linux"

    [[Thrift.download]]
    sha256 = "89a3c8bd5a2f8d0239d44f0450557e72c1f238e9d5887b75e9b058795a5ad207"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Thrift]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef18fc2cfd095193062b35b59f0668ed328ec6c3"
libc = "musl"
os = "linux"

    [[Thrift.download]]
    sha256 = "fcec9e2b9f473aa0e4847915320372cc88f20f60bdb08dfc7e121d378a990779"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.x86_64-linux-musl-cxx03.tar.gz"
[[Thrift]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2657162ea094fe60bf5db98724e2729481c8d18"
libc = "musl"
os = "linux"

    [[Thrift.download]]
    sha256 = "e841973a4805a1dd136b4318a54af6346c81e6d3e42b5000de8c0c6fcd8acecd"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.x86_64-linux-musl-cxx11.tar.gz"
[[Thrift]]
arch = "x86_64"
git-tree-sha1 = "7b9a1cb9f563ef1bf7296100b1600331e44b67c1"
os = "freebsd"

    [[Thrift.download]]
    sha256 = "98dbdc4af002fa8d2010f19290d54ace1461c072518f754984da3b4df1b69437"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.x86_64-unknown-freebsd.tar.gz"
[[Thrift]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "669a0badf27f40098ecaf8bb709b50c37ac2b972"
os = "windows"

    [[Thrift.download]]
    sha256 = "85787e7916136422427c4acde254c558db519172a1f9394028ec5bbb87af9ca5"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Thrift]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e5f2a084a9b21ad9d05e041faacb29f1da1ccc8"
os = "windows"

    [[Thrift.download]]
    sha256 = "b36d7f23e4e1e022e66cdc895d3c74ac24e458744232c75ff4b2681b78a6c6dd"
    url = "https://github.com/JuliaBinaryWrappers/Thrift_jll.jl/releases/download/Thrift-v0.21.0+0/Thrift.v0.21.0.x86_64-w64-mingw32-cxx11.tar.gz"
